---
- hosts: localhost
  connection: local

  tasks:
    - name: "Find all files"
      find:
        paths: '{{ playbook_dir }}'
        patterns: '*.tex'
        recurse: yes
      register: files
    - name: Fix all files
      shell: 'vlna -l {{ item.path }}'
      register: echo
      loop: '{{ files.files }}'
      changed_when: '"changes: 0" not in echo.stderr'
      loop_control:
        label: "{{ echo.stderr_lines[1][10:] }}"